use guvi;
-- Q1 ANS
SELECT * FROM CUSTOMERS;
SELECT CUSTOMERID,FIRSTNAME,LASTNAME,DATE_of_BIRTH,DATE_FORMAT(FROM_DAYS(DATEDIFF(NOW(),DATE_of_BIRTH)),'%Y') + 0 AS AGE
FROM CUSTOMERS;

-- Q2 ANS
SELECT * FROM CUSTOMERS;
SELECT FIRSTNAME,char_length(FIRSTNAME) AS CHARACTERS,
COUNT(FIRSTNAME)
FROM CUSTOMERS
GROUP BY (FIRSTNAME);

-- Q3 ANS 
SELECT YEAR(ORDERDATE) AS YEARS,quarter(ORDERDATE) AS QUARTERS,
COUNT(*) AS NUMBER_OF_ORDERS
FROM ORDERS
GROUP BY YEAR(ORDERDATE),quarter(ORDERDATE)
ORDER BY COUNT(*) ;

-- Q4 ANS 
select YEAR(ORDERDATE) AS YEARS,WEEK(ORDERDATE) AS WEEKS,
COUNT(*) AS NUMBER_OF_ORDERS
FROM ORDERS
GROUP BY YEAR(ORDERDATE),WEEK(ORDERDATE)
ORDER BY COUNT(*) ;
 
-- Q6 ANS 
SELECT DAYNAME(PRODUCTID) AS DAYNAME,
COUNT(PRODUCT) AS COUNT_OF_DELIVERY
FROM PRODUCTS
GROUP BY DAYNAME(PRODUCTID)
ORDER BY COUNT(*) DESC;

-- Q7 ANS 

SELECT ORDERID,CUSTOMERID,avg(TOTAL_ORDER_AMOUNT) AS AVERAGE_REVENUE
 FROM ORDERS
GROUP BY ORDERID,CUSTOMERID;

-- Q8 ANS
SELECT * FROM SUPPLIERS;
SELECT SUPPLIERID,COMPANYNAME,CITY,COUNTRY
FROM SUPPLIERS;
